const RESEARCH_DATA = {
    "weedout": {
        title: "WeedOut: Semi-Supervised Weed Management",
        venue: "IFIP IoT 2023",
        overviewImage: "",
        problemImage: "",
        methodologyImage: "Image/weedout_overview.jpg",
        innovationImage: "Image/DTW.jpg",
        resultsImage: "Image/weedout_result.jpg",
        overviewCaption: "Illustration of proposed A-CPS with WeedOut.",
        problemCaption: "",
        methodologyCaption: "",
        innovationCaption: "Illustration of Dynamic Time Warping (DTW).",
        resultsCaption: "Weeds and primary crops identified using WeedOut.",
        overview: "A semi-supervised, non-CNN Agriculture Cyber-Physical System (A-CPS) that classifies weeds based on crop profile, shape, and size, requiring no prior training.",
        problem: "Deep learning models require massive labeled datasets and struggle to generalize to unseen weed species or different growth stages. Farmers need a 'plug-and-play' solution that adapts instantly.",
        methodology: "Uses a 2-pass connected component algorithm to extract individual crop shapes from drone imagery. Generates 'Profile Plots' (width vs. length graphs) for each plant. Clusters these plots using Dynamic Time Warping (DTW) to group similar-looking plants. The farmer labels just one cluster, and the system propagates the label to all matching plants.",
        novelty: "Eliminates the need for large training datasets. Uses shape-based time-series matching (DTW) instead of visual feature extraction, making it robust to lighting and color variations.",
        results: "Achieved 93% classification accuracy with minimal human input (labeling 1-2 clusters). Demonstrated robust performance even when crops overlap.",
        paperLink: "IFIP-IoT_2023_WeedOut_SRF.pdf",
        githubLink: "https://github.com/kirankkethineni/WeedOut"
    },
    "chroma-sense": {
        title: "Chroma-Sense: Memory-Efficient Edge AI",
        venue: "IEEE CAI 2024",
        overviewImage: "",
        problemImage: "",
        methodologyImage: "Image/chromasense_methodology.jpg",
        innovationImage: "Image/chromasense_innovation.jpg",
        resultsImage: "Image/chromasense_results.jpg",
        overviewCaption: "",
        problemCaption: "",
        methodologyCaption: "Proposed architecture for serial processing.",
        innovationCaption: "Illustration of complexity reduction in the feature extractor.",
        resultsCaption: "Memory reduction achieved by proposed architecture.",
        overview: "A memory-efficient sequential multi-channel CNN architecture designed for plant disease classification on resource-constrained edge devices / IoT.",
        problem: "Standard CNNs (like ResNet, MobileNet) are often too heavy for edge devices with limited RAM and Flash memory. Sending data to the cloud for processing introduces latency, requires connectivity, and raises privacy concerns.",
        methodology: "Introduced 'Serial Multi-Channel Processing': instead of processing RGB channels simultaneously, it processes each channel sequentially using a shared feature extractor. This weight-sharing drastically reduces the model's parameter count. It employs 'Global Max Pooling' to better capture localized disease spots compared to average pooling.",
        novelty: "The first architecture to decouple color channels for memory efficiency in agricultural AI. It reduces the model width by ~66% while reusing the same weights, making it fit on microcontrollers (TinyML).",
        results: "Achieved 93% classification accuracy on PlantVillage datasets. Reduced Peak RAM usage by 25% and Flash memory usage by 60% compared to MobileNetV2. Validated on Arduino Nicla Vision, OpenMV H7, OpenMV H7 Plus running at ~8 FPS.",
        paperLink: "IEEE-CAI_2025_ChromaSense.pdf",
        githubLink: "https://github.com/kirankkethineni/ChromaSense"
    },
    "spraycraft": {
        title: "SprayCraft: Precision Drone Routing",
        venue: "arXiv 2024",
        overviewImage: "Image/spraycraft_overview.jpg",
        problemImage: "",
        methodologyImage: "Image/spraycraft_methodology.jpg",
        innovationImage: "",
        resultsImage: "Image/spraycraft_result.jpg",
        overviewCaption: "Benefits of Variable-Rate Precision Spraying",
        problemCaption: "",
        methodologyCaption: "Proposed workflow for SprayCraft",
        innovationCaption: "",
        resultsCaption: "Drone route, height and dosage prescription for a given diseased locations in a farm",
        overview: "Graph-based route optimization algorithm for variable-rate precision spraying, identifying disease hotspots to minimize chemical usage.",
        problem: "Uniform 'blanket spraying' wastes expensive chemicals and harms the environment. Drones need intelligent flight paths that prioritize high-infection areas ('hotspots') to apply variable dosages efficiently.",
        methodology: "Models the farmland as a spatial graph where nodes are disease locations. Uses Message Passing (inspired by GNNs) to diffuse infection probability to neighbors, identifying 'hotspots' (dense infection clusters). Solves the Traveling Salesman Problem (TSP) using Christofides algorithm to find the optimal visitation order, then generates Boustrophedon (serpentine) paths for coverage.",
        novelty: "Integrates spatial disease dynamics with robotic path planning. Can adapt pesticide intensity by varying flight altitude/speed for drones that lack variable-rate nozzles.",
        results: "Significantly reduces pesticide volume by targeting hotspots with higher intensity. Generated routes are near-optimal in length, saving battery life compared to standard coverage patterns.",
        paperLink: "arXiv_2025-XXX_SprayCraft.pdf",
        githubLink: "https://github.com/kirankkethineni/SprayCraft"
    },
    "semantic-search": {
        title: "Semantic-Search: Explainable Classification",
        venue: "IEEE TAFE 2025",
        overviewImage: "",
        problemImage: "Image/SemanticSearch_Problem.JPG",
        methodologyImage: "Image/SemanticSearch_Methodology.JPG",
        innovationImage: "Image/SemanticSearch_Innovation.JPG",
        resultsImage: "Image/SemanticSearch_Result.JPG",
        overviewCaption: "",
        problemCaption: "Illustration of Data Driven Approach.",
        methodologyCaption: "Workflow of the proposed semantic-search framework.",
        innovationCaption: "Illustration of Knowledge-Driven Approach.",
        resultsCaption: "Classification results.",
        overview: "A knowledge-driven classification framework that interprets high-level semantic features (visual patterns, colors) rather than just pixel correlations.",
        problem: "Deep learning 'black boxes' lack interpretability—farmers don't know why a plant disease was classified as the presented label. They also struggle with rare diseases where data is scarce.",
        methodology: "Integrates Natural Language Processing (NLP) to extract semantics (e.g., 'brown spots', 'yellow halo') from text descriptions to build a knowledge base. During inference, a CNN detects these specific semantic features in the image, and a database query classifies the disease based on the logic rule (e.g., IF has_spots AND has_yellow_halo THEN disease_X).",
        novelty: "Decouples feature detection from classification. Can classify new/unseen diseases effectively if their semantic rules are added to the database, without retraining the CNN.",
        results: "Achieved 90% accuracy across 11,000 images covering 21 diseases. Offers superior scalability and human-readable explanations for every diagnosis.",
        paperLink: "IEEE-TAFE_2025-TAFE-02-0037-2025-R3_Semantic-Search.pdf",
        githubLink: "https://github.com/kirankkethineni/Semantic-Search"
    },
    "soil": {
        title: "SOIL: Privacy-First On-Device AI",
        venue: "IEEE OCIT 2025",
        overviewImage: "",
        problemImage: "Image/soil_problem.jpg",
        methodologyImage: "Image/soil_methodology.jpg",
        innovationImage: "",
        resultsImage: "Image/soil_result.jpg",
        overviewCaption: "",
        problemCaption: "Traditional AI application architecture.",
        methodologyCaption: "Overview of proposed SOIL.",
        innovationCaption: "",
        resultsCaption: "Inference latency of proposed SOIL framework across devices.",
        overview: "A privacy-first framework for leaf disease diagnosis that executes AI models directly within a mobile web browser using WebAssembly.",
        problem: "Cloud-based diagnosis risks data privacy and requires internet access, which is often unreliable in remote fields. Native apps create installation friction.",
        methodology: "Leverages TensorFlow.js and WebGL/WASM acceleration to run edge-optimized CNNs (derived from Chroma-Sense) entirely client-side in the browser. No image data ever leaves the user's device.",
        novelty: "Zero-install, cross-device compatible, and privacy-preserving by design. Optimizing heavy CNN computations for JavaScript execution environments.",
        results: "Validated on iPhone, Android, and Windows with ~16ms inference latency (iPhone 14). Preserves 100% data privacy while maintaining high diagnostic accuracy (up to 96%).",
        paperLink: "OCIT_2025_SOIL.pdf",
        githubLink: "https://github.com/kirankkethineni/Soil"
    },
    "xpress-weed": {
        title: "XpressWeed: Few-Shot Adaptation",
        venue: "IEEE SusTech 2026",
        overviewImage: "",
        problemImage: "",
        methodologyImage: "Image/xpress_weed_Method.jpg",
        innovationImage: "Image/xpress_weed_Innovation.jpg",
        resultsImage: "Image/xpress_weed_result.jpg",
        overviewCaption: "",
        problemCaption: "",
        methodologyCaption: "Workflow of the proposed XpressWeed framework.",
        innovationCaption: "Feature landscapes showing robustness from texture priors and adaptation with MAML.",
        resultsCaption: "Validation results and PR curvesof the MAML-adapted model.",
        overview: "A meta-learning framework that treats plant leaves as 'textures' rather than objects, enabling rapid adaptation to new weed species with minimal data.",
        problem: "Weed species vary immensely by region. Training a universal model is impossible. Generic few-shot learning fails due to complex overlaps and non-rigid deformations of leaves.",
        methodology: "Combines texture-based pre-training with Model-Agnostic Meta-Learning (MAML). The model learns robust leaf texture priors (veins, surface patterns) first, then uses meta-learning to fine-tune itself for new species using just a handful of labeled examples (12-shot learning).",
        novelty: "Shifts focus from object detection to texture analysis. Enables 'rapid adaptation' where a farmer can teach the model a new weed in minutes.",
        results: "Achieved 85% accuracy on unseen weed species using just 80 training images, significantly outperforming traditional MAML (48%).",
        paperLink: "XpressWeed.pdf",
        githubLink: "https://github.com/kirankkethineni/XpressWeed"
    }
};
